---
title: "Identifiers for commemorations and their precedence in the lectionary"
---





## Precedence

Commemorations with fixed dates can fall on the same day as a Sunday.  The following constants are used to rank their precedence.



- `PRINCIPAL_FEAST` = 1
- `HOLY_DAY_1` = 2
- `SUNDAY` = 3
- `HOLY_DAY_2` = 4
- `LESSER_FEAST` = 5 # Not yet implemented
- `OTHER_DAY` = 6



## Commemorations (feasts and fasts)

Feast days are identified by constant values listed on this page. You can construct the liturgical day for a feast in a given liturgical year using one of the constants.

```{julia}
#| warning: false
using Lectionary
Commemoration(Lectionary.FEAST_ALL_SAINTS)
```


### Principal feasts (precedence 1)

- `FEAST_EASTER`
- `FEAST_ASCENSION`
- `FEAST_PENTECOST`
- `FEAST_TRINITY`
- `FEAST_ALL_SAINTS`
- `FEAST_CHRISTMAS`
- `FEAST_EPIPHANY`


### Holy Days (precedence 2)

- `FEAST_HOLY_NAME`
- `FEAST_PRESENTATION`
- `FEAST_TRANSFIGURATION`

### Sundays (precedence 3)

- see [separate page](./sundays.qmd)

### Holy Days (precedence 4)

- `FEAST_ANNUNCIATION`
- `FEAST_VISITATION`
- `FEAST_SAINT_JOHN`
- `FEAST_HOLY_CROSS`
- `FEAST_SAINT_STEPHEN`
- `FEAST_HOLY_INNOCENTS`
- `FEAST_SAINT_JOSEPH`
- `FEAST_MARY_MAGDALENE`
- `FEAST_MARY_THE_VIRGIN`
- `FEAST_MICHAEL_AND_ALL_ANGELS`
- `FEAST_SAINT_JAMES_JERUSALEM`
- `FEAST_INDEPENDENCE_DAY`
- `FEAST_THANKSGIVING_DAY`
- `FEAST_CONFESSION_OF_PETER`
- `FEAST_CONVERSION_OF_PAUL`
- `FEAST_SAINT_MATTHIAS`
- `FEAST_SAINT_MARK`
- `FEAST_SAINTS_PHILIP_AND_JAMES`
- `FEAST_SAINT_BARNABAS`
- `FEAST_SAINT_JOHN_BAPTIST`
- `FEAST_SAINT_JAMES_APOSTLE`
- `FEAST_SAINT_BARTHOLOMEW`
- `FEAST_SAINT_MATTHEW`
- `FEAST_SAINT_LUKE`
- `FEAST_SAINTS_SIMON_AND_JUDE`
- `FEAST_SAINT_ANDREW`
- `FEAST_SAINT_THOMAS`
