---
title: "API documentation: liturgical years, seasons, and days"
---


## The liturgical year and seasons

### Types

`LiturgicalYear` 

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
using Lectionary
@doc LiturgicalYear
```
:::




### Functions for working with liturgical years


`liturgical_year`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc liturgical_year
```
:::


`lectionary_year`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc lectionary_year
```
:::



`daily_office_year`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc daily_office_year
```
:::


`date_range`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc date_range
```
:::

`kalendar`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc kalendar
```
:::

`sundays`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc sundays
```
:::


`principal_feasts`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc principal_feasts
```
:::

`holy_days`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc holy_days
```
:::

### Functions for working with liturgical seasons


`advent_season`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc advent_season
```
:::

`advent_sundays`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc advent_sundays
```
:::

`christmastide`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc christmastide
```
:::

`christmas_sundays`



:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc christmas_sundays
```
:::

`epiphany_season`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc epiphany_season
```
:::

`epiphany_sundays`


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc epiphany_sundays
```
:::



`lent_season`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc lent_season
```
:::

`lent_sundays`


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc lent_sundays
```
:::

`eastertide`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc eastertide
```
:::


`easter_sundays`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc easter_sundays
```
:::


`pentecost_season`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc pentecost_season
```
:::

`pentecost_sundays`


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc pentecost_sundays
```
:::

## Liturgical days

### Concrete subtypes of the `LiturgicalDay`

`Sunday`: see [separate page](./sundays.qmd)

`Commemoration`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc Commemoration
```
:::

`OtherDay`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc OtherDay
```
:::


### Functions for working with liturgical days


`name`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc name
```
:::



`civildate`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc civildate
```
:::

`liturgical_day`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc liturgical_day
```
:::

`weekday`


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc weekday
```
:::





### Functions for constructing particular liturgical days


`advent`


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc advent
```
:::


`christmas_day`


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc christmas_day
```
:::


`christmas`



:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc christmas
```
:::

`epiphany_day`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc epiphany_day
```
:::


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc epiphany_day
```
:::

`epiphany`


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc epiphany
```
:::

`ash_wednesday`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc ash_wednesday
```
:::


`ash_wednesday_date`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc ash_wednesday_date
```
:::


`lent`



:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc lent
```
:::


`palm_sunday`


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc palm_sunday
```
:::


`holyweek`


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc holyweek
```
:::


`good_friday`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc good_friday
```
:::


`easter_sunday`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc easter_sunday
```
:::


`pentecost_day`


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc pentecost_day
```
:::

`trinity`


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc trinity
```
:::


`ascension`


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc ascension
```
:::

`thanksgiving`

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc thanksgiving
```
:::

